### ISSUE TITLE
Test `verify_extern_16bit_math_retry` in release mode fails and passes randomly

### ISSUE THREAD

**Issue by Melirius** [microsoft/lepton_jpeg_rust#108]
Testing current `main` with release I found out that `verify_extern_16bit_math_retry` test sometimes passes and sometimes not. First discovered testing all the test bundle, but then confirmed in running just this single test.
<details>
  <summary>Log</summary>
  
```
ivan@ivan-5950:~/lepton_jpeg_rust$ RUSTFLAGS='-C target-feature=+avx2 -C target-feature=+lzcnt' cargo test --release
    Finished `release` profile [optimized + debuginfo] target(s) in 0.03s
     Running unittests src/lib.rs (target/release/deps/lepton_jpeg-0a5595ec095fec82)

running 49 tests
test helpers::test_copy_cstring_utf8_to_buffer ... ok
...
test structs::lepton_file_writer::test_slrcity ... ok

test result: ok. 49 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.55s

     Running unittests src/main.rs (target/release/deps/lepton_jpeg_util-cfb18bc90b5fdf6c)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/end_to_end.rs (target/release/deps/end_to_end-bc84d695abaf6a00)

running 105 tests
test verify_decode::file_07___colorswap__ ... ok
...
test verify_16bitmath ... ok
test verify_extern_16bit_math_retry ... FAILED
test verify_extern_interface_supports_decompression_with_zeros_in_dqt_tables::file_1___zeros_in_dqt_tables__ ... ok
...
test verify_encode::file_10___hq__ ... ok

failures:

---- verify_extern_16bit_math_retry stdout ----
reading /home/ivan/lepton_jpeg_rust/images/mathoverflow_16.lep
reading /home/ivan/lepton_jpeg_rust/images/mathoverflow.jpg
thread 'verify_extern_16bit_math_retry' panicked at tests/end_to_end.rs:306:9:
assertion `left == right` failed
  left: 1000
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    verify_extern_16bit_math_retry

test result: FAILED. 104 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.60s

error: test failed, to rerun pass `--test end_to_end`


ivan@ivan-5950:~/lepton_jpeg_rust$ RUSTFLAGS='-C target-feature=+avx2 -C target-feature=+lzcnt' cargo test --release
   Compiling lepton_jpeg v0.4.0 (/home/ivan/lepton_jpeg_rust)
    Finished `release` profile [optimized + debuginfo] target(s) in 3.40s
     Running unittests src/lib.rs (target/release/deps/lepton_jpeg-0a5595ec095fec82)

running 49 tests
test helpers::test_copy_cstring_utf8_to_buffer ... ok
...
test structs::lepton_file_writer::test_slrcity ... ok

test result: ok. 49 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.56s

     Running unittests src/main.rs (target/release/deps/lepton_jpeg_util-cfb18bc90b5fdf6c)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/end_to_end.rs (target/release/deps/end_to_end-bc84d695abaf6a00)

running 105 tests
test verify_decode::file_07___colorswap__ ... ok
...
test verify_decode_external_interface_with_use_16bit_dc_estimate::file_26___slrindoor__ ... ok
test verify_extern_16bit_math_retry ... FAILED
test verify_decode_external_interface_with_use_16bit_dc_estimate::file_30___trunc__ ... ok
...
test verify_encode::file_10___hq__ ... ok

failures:

---- verify_extern_16bit_math_retry stdout ----
reading /home/ivan/lepton_jpeg_rust/images/mathoverflow_16.lep
reading /home/ivan/lepton_jpeg_rust/images/mathoverflow.jpg
thread 'verify_extern_16bit_math_retry' panicked at tests/end_to_end.rs:306:9:
assertion `left == right` failed
  left: 1000
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    verify_extern_16bit_math_retry

test result: FAILED. 104 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.60s

error: test failed, to rerun pass `--test end_to_end`


ivan@ivan-5950:~/lepton_jpeg_rust$ RUSTFLAGS='-C target-feature=+avx2 -C target-feature=+lzcnt' cargo test --release
   Compiling lepton_jpeg v0.4.0 (/home/ivan/lepton_jpeg_rust)
    Finished `release` profile [optimized + debuginfo] target(s) in 3.38s
     Running unittests src/lib.rs (target/release/deps/lepton_jpeg-0a5595ec095fec82)

running 49 tests
test helpers::test_copy_cstring_utf8_to_buffer ... ok
...
test structs::lepton_file_writer::test_slrcity ... ok

test result: ok. 49 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.55s

     Running unittests src/main.rs (target/release/deps/lepton_jpeg_util-cfb18bc90b5fdf6c)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/end_to_end.rs (target/release/deps/end_to_end-bc84d695abaf6a00)

running 105 tests
test verify_decode::file_07___colorswap__ ... ok
...
test extern_interface_decompress_chunked ... ok
test verify_extern_16bit_math_retry ... ok
test verify_decode_external_interface_with_use_16bit_dc_estimate::file_24___slrcity__ ... ok
...
test verify_encode::file_10___hq__ ... ok

test result: ok. 105 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.63s

   Doc-tests lepton_jpeg

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

</details>

rustc 1.81.0 (eeb90cda1 2024-09-04)

To reproduce try to test with `RUSTFLAGS='-C target-feature=+avx2 -C target-feature=+lzcnt' cargo test --release`

Error string is "at src/structs/lepton_file_reader.rs line 50", so the problem is inside `process_buffer`

**Comment by mcroomp** [comment]
I believe this is fixed now with the change in Multiplexer.rs:424

**Comment by Melirius** [comment]
Yes, seems so. Thank you!
